server:
  port: 8888

spring:
  application:
    name: Configuration
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
  config:
    import: optional:consult